### ISSUE TITLE
murder nightmare murder murder murder murder nightmare nightmare nightmare hell death murder nightmare nightmare murder

### ISSUE THREAD

**Issue by Lisenaaaa** [Polyfrost/PolyHelper#3]
![image](https://user-images.githubusercontent.com/69115669/197652077-6e92932e-cc43-48de-b9bc-aec001d77551.png)

stuff like [sapphire](https://www.sapphirejs.com/) or even just doing _slash commands_ exists for a reason

hell, the discord.js guide has an example that's so much better than this

w h y a r e y o u d o i n g i t t h i s w a y

![image](https://user-images.githubusercontent.com/69115669/197652431-ec30f002-9ea6-49db-aa0d-ac0c26c103cc.png)

i know y'all hate me now, but seriously? do y'all want me to relearn djs and all that stuff so that i can make a pr that makes this code not be awful?

**Comment by Wyvest** [comment]
> i know y'all hate me now, but seriously? do y'all want me to relearn djs and all that stuff so that i can make a pr that makes this code not be awful?

Yes

**Comment by KTibow** [comment]
are you on the right branch

**Comment by Lisenaaaa** [comment]
all three branches don't use a command framework

**Comment by KTibow** [comment]
fine im creating one rn and wasting a load of time

**Comment by KTibow** [comment]
[done](https://github.com/KTibow/SkyAnswers/commits/rewrite)

**Comment by RuinTD** [comment]
i just noticed this closed issue lol
